"""
Utilities for handling and processing image files.
"""
import os
import uuid
import shutil
from pathlib import Path

from config import PLOTS_DIR


def make_persistent_copy(image_path):
    """
    Create a persistent copy of an image with a unique filename.
    
    This prevents images from being overwritten when new plots
    are generated by PandasAI.
    
    Args:
        image_path (str): Path to the original image file
        
    Returns:
        str or None: Path to the persistent copy, or None if copying failed
    """
    if not os.path.exists(image_path):
        return None
    
    # Create a unique filename using UUID
    unique_id = uuid.uuid4()
    file_extension = Path(image_path).suffix
    unique_filename = os.path.join(PLOTS_DIR, f"plot_{unique_id}{file_extension}")
    
    # Copy the file
    try:
        shutil.copy2(image_path, unique_filename)
        return unique_filename
    except Exception as e:
        print(f"Error copying image: {e}")
        return image_path


def is_image_path(path):
    """
    Check if a string is a path to an image file.
    
    Args:
        path (str): The path to check
        
    Returns:
        bool: True if the path looks like an image file path
    """
    if not isinstance(path, str):
        return False
        
    image_extensions = ['.png', '.jpg', '.jpeg', '.gif', '.bmp', '.svg']
    return any(path.lower().endswith(ext) for ext in image_extensions)